<a href="https://colab.research.google.com/github/vavvari/MAT421/blob/main/ModuleD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.1 Introduction**

Linear algebra is a field of mathematics with many applications in data science and machine learning. The use of these concepts is present in various algorithms, and concepts like vector spaces, orthogonality, eigenvalues, matrix decomposition will be expanded upon to further our understanding of linear regression and principal component analysis.

**1.2 Elements of Linear Spaces**

**1.2.1 Linear Combinations**

A linear space is given from linear combination, which are new vectors that are made by multiplying each vector in a subset by some constant and adding the values together.

Definition: A linear subspace of V is a subset U ⊆ V
that is closed under vector addition and scalar multiplication.

A span of a set of vectors is also a linear subspace, represented as -

span(w1, . . . , wm) ={ m∑_j=1 α_j w_j : α1, . . . , αm ∈ R}\

**1.2.2 Orthogonality**

The use of orthogonal bases in linear algebra can simplify our mathematical representations and reveal information about the problem we are pursuing a solution for. Given vectors u and v the norm and inner product is
- ⟨u, v⟩ = u · v = ∑n u_i*v_i and ∥u∥ =√ ∑n (u_i) ^ 2

A list of vectors is said to be orthonormal if the u_i vectors are
pairwise orthogonal and each has a norm of 1.

If U ⊆ V is a linear subspace with orthonormal basis (q1, . . . , q_m), we define the orthogonal projection of v ∈ V on U as -

PU v =∑_j=1 ⟨v, q_j⟩*q_j

This technique can be used to confirm optimality of vectors used and come up with the best approximation of orthonormality.

**1.2.3 Gram-Schmidt Process**

We use the Gram-Schmidt algorithm to find an orthonormal basis. Vectors a_i are added one by one after removing the previously used orthogonal projection.

The Gram-Schmidt theorem states that with (a_1, . . . , a_m) in R_n that is  linearly independent, then there must exist an orthonormal basis (q_1, . . . , q_m) with span(a_1, . . . , a_m).

**1.2.4 Eigenvalues and Eigenvectors**

When we have a square matrix A of real numbers, then we say that λ ∈ R is an eigenvalue of A if there exists a nonzero vector x such that Ax = λx. We then refer to the vector x here as an eigenvector, but not every matrix has eigenvalues.

We can use Python code to calculate the eigenvalues and therefore eigenvectors of a given matrix:

In [4]:
# imports needed to calculate eigenvalue
import numpy as np
from numpy.linalg import eig

a = np.array([[4, 4, 8],
              [1, 6, 10],
              [4, 6, 8]])

# eigenvalue function call
w,v=eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [17.32501772  2.28889581 -1.61391353]
E-vector [[-0.53955301 -0.73867428 -0.32054824]
 [-0.58355188  0.65269941 -0.73792203]
 [-0.60691824 -0.16835613  0.59390227]]


**1.3 Linear Regression**

Linear regression models depend linearly on their unknown parameters which often can make them easier to fit that non-linear models. The linear least squares problem can be solved by using QR decomposition. The Gram-Schmidt process is used to create an orthonormal basis span, which is written as QR decomposition A = QR.

Python code can be used to figure out the A, Q, and R in our decomposition with ease -

In [6]:
# imports for linear algebra functions
import pprint
import scipy
import scipy.linalg

# given square matrix A
A = scipy.array([[12, -51, 4],
                  [6, 167, -68],
                  [-4, 24, -41]])
# use linalg library to find decomposition
Q, R = scipy.linalg.qr(A)

print("A")
pprint.pprint(A)

print("Q")
pprint.pprint(Q)

print("R:")
pprint.pprint(R)

A
array([[ 12, -51,   4],
       [  6, 167, -68],
       [ -4,  24, -41]])
Q
array([[-0.85714286,  0.39428571,  0.33142857],
       [-0.42857143, -0.90285714, -0.03428571],
       [ 0.28571429, -0.17142857,  0.94285714]])
R:
array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])


<ipython-input-6-f659c5712b76>:6: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  A = scipy.array([[12, -51, 4],


Solving least squares problems can be done in a similar way, with using the least squares regression β=(A^T*A)^−1*A^T*Y to make sense of a problem in which we are unable to use matrix inverse to solve Ax = b.

In [8]:
# imports for least squares regression
import numpy as np
from scipy import optimize

# establish random x and y values for problem
x = np.linspace(0, 1, 101)
y = 1 + x + x * np.random.random(len(x))
# assemble matrix A
A = np.vstack([x, np.ones(len(x))]).T

# make column vector for y
y = y[:, np.newaxis]

# regression
alpha = np.dot((np.dot(np.linalg.inv(np.dot(A.T,A)),A.T)),y)
print(alpha)

[[1.68674527]
 [0.95277017]]
